# Generated by Django 5.0.1 on 2024-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
